export const SALES_FETCH_SALES_BEGIN = 'SALES_FETCH_SALES_BEGIN';
export const SALES_FETCH_SALES_SUCCESS = 'SALES_FETCH_SALES_SUCCESS';
export const SALES_FETCH_SALES_FAILURE = 'SALES_FETCH_SALES_FAILURE';
export const SALES_FETCH_SALES_DISMISS_ERROR = 'SALES_FETCH_SALES_DISMISS_ERROR';
